
/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

CREATE DATABASE IF NOT EXISTS myPodDB;
 use myPodDB;

CREATE TABLE `registre` IF NOT EXISTS (
  `nom` varchar(100) NOT NULL,
  `prenom` varchar(100) NOT NULL,
  `adressemail` varchar(100) NOT NULL,
  `motdepasse` varchar(100) NOT NULL,
  `pseudo` varchar(100) NOT NULL,
  `id` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

ALTER TABLE `registre`
  ADD PRIMARY KEY (`id`);

ALTER TABLE `registre`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
COMMIT;


INSERT INTO registre (nom, prenom, adressemail, motdepasse, pseudo) VALUES ('dine', 'dine', 'dine@dine.com', 'dine', 'dine');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
